name: build:javascript

on:
  workflow_call:
    secrets:
      PLANTON_CLOUD_SERVICE_CLIENT_ID:
        required: true
      PLANTON_CLOUD_SERVICE_CLIENT_SECRET:
        required: true
    inputs:
      PLANTON_CLOUD_SERVICE_CLI_ENV:
        required: true
        type: string
      PLANTON_CLOUD_ARTIFACT_STORE_ID:
        required: true
        type: string

jobs:
  build-code:
    runs-on: ubuntu-latest
    name: javascript build
    steps:
      - uses: actions/checkout@v3
      # https://github.com/vercel/next.js/issues/38330#issuecomment-1178913616
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: setup yarn
        run: |
          corepack enable
          corepack prepare yarn@v3.2.3 --activate
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - uses: plantoncloud/gh-action-build-javascript@main
        with:
          planton_cloud_service_cli_env: ${{ inputs.PLANTON_CLOUD_SERVICE_CLI_ENV }}
          planton_cloud_service_client_id: ${{ secrets.PLANTON_CLOUD_SERVICE_CLIENT_ID }}
          planton_cloud_service_client_secret: ${{ secrets.PLANTON_CLOUD_SERVICE_CLIENT_SECRET }}
          planton_cloud_artifact_store_id: ${{ inputs.PLANTON_CLOUD_ARTIFACT_STORE_ID }}
      - name: zip artifacts
        run: zip build.zip build/* build/.next build/node_modules/.bin -r
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-zip
          path: build.zip
          if-no-files-found: ignore
